Milestone 2: Components
idgm5/calculator pull request #2
Opened 2020-07-17 21:44 UTC by idgm5

I created the basic components for the project which includes the classes to display the calculator buttons and the final result as the requirements suggested.

**Requirements**
1. Prepare the directory structure
2. Implement the App component
3. Implement the Display component
4. Implement the Button component
5. Implement the ButtonPanel component

2020-07-19 14:21 UTC, shloch requested changes
## Hello @idgm5 , 

Great job on what you've done
Please let's include small additions mentioned below (prior to getting a thumbs up) 

### Happy coding

2020-07-19 14:21 UTC, shloch commented on src/components/Button.js
> +
`buttonName` should be string, enforce this with `propTypes` [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/button/validateAsString.png)]

2020-07-19 14:21 UTC, shloch commented on src/components/Display.js
> +
`result` should be string (enforce with `propTypes`) [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/validateAsString.png)]

2020-07-21 03:01 UTC, bellom approved these changes
## Hi @idgm5  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-07-21 14:54 UTC, closed without merging